# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04 #EC2 ubuntu 버전

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.11
      uses: actions/setup-node@v3
      with:
        node-version: 20.11
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      working-directory: ./HappyMoney

    - name: Build
      run: npm run build --if-present
      working-directory: ./HappyMoney

      # 레포지토리를 압축시킵니다.
      # 다만 불필요한 node_module, coverage, src, test, readme, .git* 등의 파일은 제외시킵니다.
    - name: Make a zip file
      run: zip -r ./$HAPPY_MONEY.zip . -x "node_modules/*" "coverage/*" "test/*" "README.md" "*.git*"




          
